Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	all
	23	profile_hybrid_init_energies
	11	unzip_chrom_file
	35
Select jobs to execute...

[Mon May  3 21:58:04 2021]
rule profile_hybrid_init_energies:
    input: rawdata/hg19/chr7.fa
    output: output/chr7.hybrid_init.bedgraph
    jobid: 19
    wildcards: chrom_name=chr7

[Mon May  3 21:58:04 2021]
rule profile_hybrid_init_energies:
    input: rawdata/hg19/chr18.fa
    output: output/chr18.hybrid_init.bedgraph
    jobid: 52
    wildcards: chrom_name=chr18

[Mon May  3 21:58:04 2021]
rule profile_hybrid_init_energies:
    input: rawdata/hg19/chrY.fa
    output: output/chrY.hybrid_init.bedgraph
    jobid: 67
    wildcards: chrom_name=chrY

[Mon May  3 21:58:04 2021]
rule profile_hybrid_init_energies:
    input: rawdata/hg19/chr13.fa
    output: output/chr13.hybrid_init.bedgraph
    jobid: 37
    wildcards: chrom_name=chr13

[Mon May  3 21:58:04 2021]
Error in rule profile_hybrid_init_energies:
    jobid: 52
    output: output/chr18.hybrid_init.bedgraph

[Mon May  3 21:58:04 2021]
[Mon May  3 21:58:04 2021]
Error in rule profile_hybrid_init_energies:
Error in rule profile_hybrid_init_energies:
    jobid: 19
[Mon May  3 21:58:04 2021]
    jobid: 37
    output: output/chr7.hybrid_init.bedgraph
RuleException:
URLError in line 52 of /home/ethan/Documents/github/hybrid_energy/snakefile:
<urlopen error [Errno 2] No such file or directory: '/home/ethan/Documents/github/hybrid_energy/\n    python scripts/profile_hybrid_energies.py\n    '>
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2326, in run_wrapper
  File "/home/ethan/Documents/github/hybrid_energy/snakefile", line 52, in __rule_profile_hybrid_init_energies
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 517, in open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 534, in _open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1481, in file_open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1520, in open_local_file
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
Error in rule profile_hybrid_init_energies:
    output: output/chr13.hybrid_init.bedgraph

    jobid: 67

    output: output/chrY.hybrid_init.bedgraph

RuleException:
URLError in line 52 of /home/ethan/Documents/github/hybrid_energy/snakefile:
<urlopen error [Errno 2] No such file or directory: '/home/ethan/Documents/github/hybrid_energy/\n    python scripts/profile_hybrid_energies.py\n    '>
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2326, in run_wrapper
  File "/home/ethan/Documents/github/hybrid_energy/snakefile", line 52, in __rule_profile_hybrid_init_energies
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 517, in open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 534, in _open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1481, in file_open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1520, in open_local_file
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
RuleException:
URLError in line 52 of /home/ethan/Documents/github/hybrid_energy/snakefile:
<urlopen error [Errno 2] No such file or directory: '/home/ethan/Documents/github/hybrid_energy/\n    python scripts/profile_hybrid_energies.py\n    '>
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2326, in run_wrapper
  File "/home/ethan/Documents/github/hybrid_energy/snakefile", line 52, in __rule_profile_hybrid_init_energies
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 517, in open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 534, in _open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1481, in file_open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1520, in open_local_file
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
RuleException:
URLError in line 52 of /home/ethan/Documents/github/hybrid_energy/snakefile:
<urlopen error [Errno 2] No such file or directory: '/home/ethan/Documents/github/hybrid_energy/\n    python scripts/profile_hybrid_energies.py\n    '>
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2326, in run_wrapper
  File "/home/ethan/Documents/github/hybrid_energy/snakefile", line 52, in __rule_profile_hybrid_init_energies
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 517, in open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 534, in _open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1481, in file_open
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/urllib/request.py", line 1520, in open_local_file
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/ethan/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ethan/Documents/github/hybrid_energy/.snakemake/log/2021-05-03T215804.745820.snakemake.log
